AsignmentCSharp04_ASP/BanGiay_ASP_c4/Controllers/ColorController.cs
using BanGiay_ASP_c4.iServices;
using BanGiay_ASP_c4.Models;
using BanGiay_ASP_c4.Services;
//using AspNetCore;
using Microsoft.AspNetCore.Mvc;
//using Microsoft.CodeAnalysis.Host.Mef;
using System.Data;
using System.Diagnostics;
using System.Reflection.Metadata.Ecma335;

namespace BanGiay_ASP_c4.Controllers
{
    public class ColorController:Controller
    {
        private readonly ILogger<ColorController> _logger;
        private readonly iColor colorSer;

        public ColorController(ILogger<ColorController> logger)
        {
            _logger = logger;
            colorSer = new ColorSer();
        }

        public IActionResult show()
        {
            List<Color> colors = colorSer.getAllColor();
            return View(colors);
        }

        public IActionResult create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult create(Color c)
        {
            if (colorSer.createColor(c))
            {
                return RedirectToAction("show");
            }
            else return BadRequest();
        }
        public IActionResult details(Guid id)
        {
            var color = colorSer.getById(id);
            return View(color);
        }
        public IActionResult delete(Guid id)
        {
            if (colorSer.deleteColor(id))
            {
                return RedirectToAction("show");
            }
            else return BadRequest();
        }
        [HttpGet]
        public IActionResult edit(Guid id)
        {
            var color = colorSer.getById(id);
            return View(color);
        }

        public IActionResult edit(Color color)
        {
            if (colorSer.updateColor(color))
            {
                return RedirectToAction("show");
            }
            else return BadRequest();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AsignmentCSharp04_ASP/BanGiay_ASP_c4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BanGiay_ASP_c4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BanGiay_ASP_c4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BanGiay_ASP_c4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ShowRole">ShowRole</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ShowColor">ShowColor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ShowMetarial">ShowMetarial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ShowUser">ShowUser</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ShowProduct">ShowProduct</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Color" asp-action="show">show</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BanGiay_ASP_c4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>